# .github/workflows/push.yml

# name of our action
name: Trigger monorepo api build

# the event that will trigger the action
on:
  workflow_dispatch:
  push:
    branches: [ main ]

# what the action will do
jobs:
  deploy_api:
    name: Deploy api
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/github-script@v5
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
          owner: 'murshidazher',
          repo: 'budget-system',
          workflow_id: 'workflows/push-api.yml',
          ref: 'main',
          inputs: {
            message: '${{ github.event.head_commit.message }}',
          },
          });
        debug: true
